name: Update README with releases

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update README with releases
      uses: jaynes/update-readme-with-releases@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file_path: 'README.md'
        header: '## Releases'
        max_releases: 1000 # 可选，显示最新的几个releases
